// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: taskpb.proto

package taskpb

import (
	corepb "gofarm/proto/corepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 单个任务 ============
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                            // 任务ID
	Progress      int64                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`                                // 当前进度
	IsClaimed     bool                   `protobuf:"varint,3,opt,name=is_claimed,json=isClaimed,proto3" json:"is_claimed,omitempty"`             // 是否已领取
	IsUnlocked    bool                   `protobuf:"varint,4,opt,name=is_unlocked,json=isUnlocked,proto3" json:"is_unlocked,omitempty"`          // 是否已解锁
	Rewards       []*corepb.Item         `protobuf:"bytes,5,rep,name=rewards,proto3" json:"rewards,omitempty"`                                   // 奖励列表
	TotalProgress int64                  `protobuf:"varint,6,opt,name=total_progress,json=totalProgress,proto3" json:"total_progress,omitempty"` // 总进度
	ShareMultiple int64                  `protobuf:"varint,7,opt,name=share_multiple,json=shareMultiple,proto3" json:"share_multiple,omitempty"` // 分享倍数 (>1 表示可分享翻倍)
	Params        []string               `protobuf:"bytes,8,rep,name=params,proto3" json:"params,omitempty"`                                     // 参数
	Desc          string                 `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc,omitempty"`                                         // 描述
	TaskType      int32                  `protobuf:"varint,10,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`               // 任务类型
	Group         int64                  `protobuf:"varint,11,opt,name=group,proto3" json:"group,omitempty"`                                     // 分组
	CondType      int64                  `protobuf:"varint,12,opt,name=cond_type,json=condType,proto3" json:"cond_type,omitempty"`               // 条件类型
	IsShowText    int64                  `protobuf:"varint,13,opt,name=is_show_text,json=isShowText,proto3" json:"is_show_text,omitempty"`       // 是否显示文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_taskpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Task) GetIsClaimed() bool {
	if x != nil {
		return x.IsClaimed
	}
	return false
}

func (x *Task) GetIsUnlocked() bool {
	if x != nil {
		return x.IsUnlocked
	}
	return false
}

func (x *Task) GetRewards() []*corepb.Item {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *Task) GetTotalProgress() int64 {
	if x != nil {
		return x.TotalProgress
	}
	return 0
}

func (x *Task) GetShareMultiple() int64 {
	if x != nil {
		return x.ShareMultiple
	}
	return 0
}

func (x *Task) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Task) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Task) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *Task) GetGroup() int64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Task) GetCondType() int64 {
	if x != nil {
		return x.CondType
	}
	return 0
}

func (x *Task) GetIsShowText() int64 {
	if x != nil {
		return x.IsShowText
	}
	return 0
}

// ============ 活跃度奖励 ============
type Active struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 0=未完成, 1=已完成, 2=未完成
	Items         []*corepb.Item         `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Active) Reset() {
	*x = Active{}
	mi := &file_taskpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Active) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Active) ProtoMessage() {}

func (x *Active) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Active.ProtoReflect.Descriptor instead.
func (*Active) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{1}
}

func (x *Active) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Active) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Active) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// ============ 任务信息汇总 ============
type TaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrowthTasks   []*Task                `protobuf:"bytes,1,rep,name=growth_tasks,json=growthTasks,proto3" json:"growth_tasks,omitempty"` // 成长任务列表
	DailyTasks    []*Task                `protobuf:"bytes,2,rep,name=daily_tasks,json=dailyTasks,proto3" json:"daily_tasks,omitempty"`    // 每日任务列表
	Tasks         []*Task                `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`                                // 其他任务
	Actives       []*Active              `protobuf:"bytes,4,rep,name=actives,proto3" json:"actives,omitempty"`                            // 活跃度奖励
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_taskpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{2}
}

func (x *TaskInfo) GetGrowthTasks() []*Task {
	if x != nil {
		return x.GrowthTasks
	}
	return nil
}

func (x *TaskInfo) GetDailyTasks() []*Task {
	if x != nil {
		return x.DailyTasks
	}
	return nil
}

func (x *TaskInfo) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *TaskInfo) GetActives() []*Active {
	if x != nil {
		return x.Actives
	}
	return nil
}

// --- 获取任务信息 ---
type TaskInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfoRequest) Reset() {
	*x = TaskInfoRequest{}
	mi := &file_taskpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoRequest) ProtoMessage() {}

func (x *TaskInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoRequest.ProtoReflect.Descriptor instead.
func (*TaskInfoRequest) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{3}
}

type TaskInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskInfo      *TaskInfo              `protobuf:"bytes,1,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfoReply) Reset() {
	*x = TaskInfoReply{}
	mi := &file_taskpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoReply) ProtoMessage() {}

func (x *TaskInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoReply.ProtoReflect.Descriptor instead.
func (*TaskInfoReply) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{4}
}

func (x *TaskInfoReply) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

// --- 领取单个任务奖励 ---
type ClaimTaskRewardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                             // 任务ID
	DoShared      bool                   `protobuf:"varint,2,opt,name=do_shared,json=doShared,proto3" json:"do_shared,omitempty"` // 是否使用分享翻倍 (true=翻倍, false=普通领取)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTaskRewardRequest) Reset() {
	*x = ClaimTaskRewardRequest{}
	mi := &file_taskpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRewardRequest) ProtoMessage() {}

func (x *ClaimTaskRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRewardRequest.ProtoReflect.Descriptor instead.
func (*ClaimTaskRewardRequest) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimTaskRewardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClaimTaskRewardRequest) GetDoShared() bool {
	if x != nil {
		return x.DoShared
	}
	return false
}

type ClaimTaskRewardReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Items            []*corepb.Item         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`                                               // 获得的物品
	TaskInfo         *TaskInfo              `protobuf:"bytes,2,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`                         // 更新后的任务信息
	CompensatedItems []*corepb.Item         `protobuf:"bytes,3,rep,name=compensated_items,json=compensatedItems,proto3" json:"compensated_items,omitempty"` // 补偿物品
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClaimTaskRewardReply) Reset() {
	*x = ClaimTaskRewardReply{}
	mi := &file_taskpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRewardReply) ProtoMessage() {}

func (x *ClaimTaskRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRewardReply.ProtoReflect.Descriptor instead.
func (*ClaimTaskRewardReply) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimTaskRewardReply) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ClaimTaskRewardReply) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

func (x *ClaimTaskRewardReply) GetCompensatedItems() []*corepb.Item {
	if x != nil {
		return x.CompensatedItems
	}
	return nil
}

// --- 批量领取任务奖励 ---
type BatchClaimTaskRewardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`                    // 任务ID列表
	DoShared      bool                   `protobuf:"varint,2,opt,name=do_shared,json=doShared,proto3" json:"do_shared,omitempty"` // 是否使用分享翻倍
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchClaimTaskRewardRequest) Reset() {
	*x = BatchClaimTaskRewardRequest{}
	mi := &file_taskpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClaimTaskRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClaimTaskRewardRequest) ProtoMessage() {}

func (x *BatchClaimTaskRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClaimTaskRewardRequest.ProtoReflect.Descriptor instead.
func (*BatchClaimTaskRewardRequest) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchClaimTaskRewardRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BatchClaimTaskRewardRequest) GetDoShared() bool {
	if x != nil {
		return x.DoShared
	}
	return false
}

type BatchClaimTaskRewardReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Items            []*corepb.Item         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TaskInfo         *TaskInfo              `protobuf:"bytes,2,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
	CompensatedItems []*corepb.Item         `protobuf:"bytes,3,rep,name=compensated_items,json=compensatedItems,proto3" json:"compensated_items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchClaimTaskRewardReply) Reset() {
	*x = BatchClaimTaskRewardReply{}
	mi := &file_taskpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClaimTaskRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClaimTaskRewardReply) ProtoMessage() {}

func (x *BatchClaimTaskRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClaimTaskRewardReply.ProtoReflect.Descriptor instead.
func (*BatchClaimTaskRewardReply) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{8}
}

func (x *BatchClaimTaskRewardReply) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchClaimTaskRewardReply) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

func (x *BatchClaimTaskRewardReply) GetCompensatedItems() []*corepb.Item {
	if x != nil {
		return x.CompensatedItems
	}
	return nil
}

// 任务状态变化通知
type TaskInfoNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskInfo      *TaskInfo              `protobuf:"bytes,1,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfoNotify) Reset() {
	*x = TaskInfoNotify{}
	mi := &file_taskpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoNotify) ProtoMessage() {}

func (x *TaskInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoNotify.ProtoReflect.Descriptor instead.
func (*TaskInfoNotify) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{9}
}

func (x *TaskInfoNotify) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

var File_taskpb_proto protoreflect.FileDescriptor

const file_taskpb_proto_rawDesc = "" +
	"\n" +
	"\ftaskpb.proto\x12\rgamepb.taskpb\x1a\fcorepb.proto\"\x86\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x03R\bprogress\x12\x1d\n" +
	"\n" +
	"is_claimed\x18\x03 \x01(\bR\tisClaimed\x12\x1f\n" +
	"\vis_unlocked\x18\x04 \x01(\bR\n" +
	"isUnlocked\x12&\n" +
	"\arewards\x18\x05 \x03(\v2\f.corepb.ItemR\arewards\x12%\n" +
	"\x0etotal_progress\x18\x06 \x01(\x03R\rtotalProgress\x12%\n" +
	"\x0eshare_multiple\x18\a \x01(\x03R\rshareMultiple\x12\x16\n" +
	"\x06params\x18\b \x03(\tR\x06params\x12\x12\n" +
	"\x04desc\x18\t \x01(\tR\x04desc\x12\x1b\n" +
	"\ttask_type\x18\n" +
	" \x01(\x05R\btaskType\x12\x14\n" +
	"\x05group\x18\v \x01(\x03R\x05group\x12\x1b\n" +
	"\tcond_type\x18\f \x01(\x03R\bcondType\x12 \n" +
	"\fis_show_text\x18\r \x01(\x03R\n" +
	"isShowText\"T\n" +
	"\x06Active\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\"\n" +
	"\x05items\x18\x03 \x03(\v2\f.corepb.ItemR\x05items\"\xd4\x01\n" +
	"\bTaskInfo\x126\n" +
	"\fgrowth_tasks\x18\x01 \x03(\v2\x13.gamepb.taskpb.TaskR\vgrowthTasks\x124\n" +
	"\vdaily_tasks\x18\x02 \x03(\v2\x13.gamepb.taskpb.TaskR\n" +
	"dailyTasks\x12)\n" +
	"\x05tasks\x18\x03 \x03(\v2\x13.gamepb.taskpb.TaskR\x05tasks\x12/\n" +
	"\aactives\x18\x04 \x03(\v2\x15.gamepb.taskpb.ActiveR\aactives\"\x11\n" +
	"\x0fTaskInfoRequest\"E\n" +
	"\rTaskInfoReply\x124\n" +
	"\ttask_info\x18\x01 \x01(\v2\x17.gamepb.taskpb.TaskInfoR\btaskInfo\"E\n" +
	"\x16ClaimTaskRewardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdo_shared\x18\x02 \x01(\bR\bdoShared\"\xab\x01\n" +
	"\x14ClaimTaskRewardReply\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.corepb.ItemR\x05items\x124\n" +
	"\ttask_info\x18\x02 \x01(\v2\x17.gamepb.taskpb.TaskInfoR\btaskInfo\x129\n" +
	"\x11compensated_items\x18\x03 \x03(\v2\f.corepb.ItemR\x10compensatedItems\"L\n" +
	"\x1bBatchClaimTaskRewardRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12\x1b\n" +
	"\tdo_shared\x18\x02 \x01(\bR\bdoShared\"\xb0\x01\n" +
	"\x19BatchClaimTaskRewardReply\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.corepb.ItemR\x05items\x124\n" +
	"\ttask_info\x18\x02 \x01(\v2\x17.gamepb.taskpb.TaskInfoR\btaskInfo\x129\n" +
	"\x11compensated_items\x18\x03 \x03(\v2\f.corepb.ItemR\x10compensatedItems\"F\n" +
	"\x0eTaskInfoNotify\x124\n" +
	"\ttask_info\x18\x01 \x01(\v2\x17.gamepb.taskpb.TaskInfoR\btaskInfoB#Z!gofarm/proto/gamepb/taskpb;taskpbb\x06proto3"

var (
	file_taskpb_proto_rawDescOnce sync.Once
	file_taskpb_proto_rawDescData []byte
)

func file_taskpb_proto_rawDescGZIP() []byte {
	file_taskpb_proto_rawDescOnce.Do(func() {
		file_taskpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskpb_proto_rawDesc), len(file_taskpb_proto_rawDesc)))
	})
	return file_taskpb_proto_rawDescData
}

var file_taskpb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_taskpb_proto_goTypes = []any{
	(*Task)(nil),                        // 0: gamepb.taskpb.Task
	(*Active)(nil),                      // 1: gamepb.taskpb.Active
	(*TaskInfo)(nil),                    // 2: gamepb.taskpb.TaskInfo
	(*TaskInfoRequest)(nil),             // 3: gamepb.taskpb.TaskInfoRequest
	(*TaskInfoReply)(nil),               // 4: gamepb.taskpb.TaskInfoReply
	(*ClaimTaskRewardRequest)(nil),      // 5: gamepb.taskpb.ClaimTaskRewardRequest
	(*ClaimTaskRewardReply)(nil),        // 6: gamepb.taskpb.ClaimTaskRewardReply
	(*BatchClaimTaskRewardRequest)(nil), // 7: gamepb.taskpb.BatchClaimTaskRewardRequest
	(*BatchClaimTaskRewardReply)(nil),   // 8: gamepb.taskpb.BatchClaimTaskRewardReply
	(*TaskInfoNotify)(nil),              // 9: gamepb.taskpb.TaskInfoNotify
	(*corepb.Item)(nil),                 // 10: corepb.Item
}
var file_taskpb_proto_depIdxs = []int32{
	10, // 0: gamepb.taskpb.Task.rewards:type_name -> corepb.Item
	10, // 1: gamepb.taskpb.Active.items:type_name -> corepb.Item
	0,  // 2: gamepb.taskpb.TaskInfo.growth_tasks:type_name -> gamepb.taskpb.Task
	0,  // 3: gamepb.taskpb.TaskInfo.daily_tasks:type_name -> gamepb.taskpb.Task
	0,  // 4: gamepb.taskpb.TaskInfo.tasks:type_name -> gamepb.taskpb.Task
	1,  // 5: gamepb.taskpb.TaskInfo.actives:type_name -> gamepb.taskpb.Active
	2,  // 6: gamepb.taskpb.TaskInfoReply.task_info:type_name -> gamepb.taskpb.TaskInfo
	10, // 7: gamepb.taskpb.ClaimTaskRewardReply.items:type_name -> corepb.Item
	2,  // 8: gamepb.taskpb.ClaimTaskRewardReply.task_info:type_name -> gamepb.taskpb.TaskInfo
	10, // 9: gamepb.taskpb.ClaimTaskRewardReply.compensated_items:type_name -> corepb.Item
	10, // 10: gamepb.taskpb.BatchClaimTaskRewardReply.items:type_name -> corepb.Item
	2,  // 11: gamepb.taskpb.BatchClaimTaskRewardReply.task_info:type_name -> gamepb.taskpb.TaskInfo
	10, // 12: gamepb.taskpb.BatchClaimTaskRewardReply.compensated_items:type_name -> corepb.Item
	2,  // 13: gamepb.taskpb.TaskInfoNotify.task_info:type_name -> gamepb.taskpb.TaskInfo
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_taskpb_proto_init() }
func file_taskpb_proto_init() {
	if File_taskpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskpb_proto_rawDesc), len(file_taskpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taskpb_proto_goTypes,
		DependencyIndexes: file_taskpb_proto_depIdxs,
		MessageInfos:      file_taskpb_proto_msgTypes,
	}.Build()
	File_taskpb_proto = out.File
	file_taskpb_proto_goTypes = nil
	file_taskpb_proto_depIdxs = nil
}
