// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: corepb.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 通用物品 ============
type Item struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 物品ID
	Count      int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                             // 数量
	ExpireTime int64                  `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 过期时间
	// field 4 reserved
	Uid           int64 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`                                 // 唯一ID
	CreateTime    int64 `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_corepb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_corepb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_corepb_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Item) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *Item) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Item) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// 物品变更
type ItemChg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`    // 物品信息
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"` // 变化量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemChg) Reset() {
	*x = ItemChg{}
	mi := &file_corepb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemChg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemChg) ProtoMessage() {}

func (x *ItemChg) ProtoReflect() protoreflect.Message {
	mi := &file_corepb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemChg.ProtoReflect.Descriptor instead.
func (*ItemChg) Descriptor() ([]byte, []int) {
	return file_corepb_proto_rawDescGZIP(), []int{1}
}

func (x *ItemChg) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ItemChg) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

// 物品背包
type ItemBag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemBag) Reset() {
	*x = ItemBag{}
	mi := &file_corepb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemBag) ProtoMessage() {}

func (x *ItemBag) ProtoReflect() protoreflect.Message {
	mi := &file_corepb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemBag.ProtoReflect.Descriptor instead.
func (*ItemBag) Descriptor() ([]byte, []int) {
	return file_corepb_proto_rawDescGZIP(), []int{2}
}

func (x *ItemBag) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_corepb_proto protoreflect.FileDescriptor

const file_corepb_proto_rawDesc = "" +
	"\n" +
	"\fcorepb.proto\x12\x06corepb\"\x80\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x1f\n" +
	"\vexpire_time\x18\x03 \x01(\x03R\n" +
	"expireTime\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\x03R\x03uid\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\x03R\n" +
	"createTime\"A\n" +
	"\aItemChg\x12 \n" +
	"\x04item\x18\x01 \x01(\v2\f.corepb.ItemR\x04item\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\"-\n" +
	"\aItemBag\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.corepb.ItemR\x05itemsB\x1cZ\x1agofarm/proto/corepb;corepbb\x06proto3"

var (
	file_corepb_proto_rawDescOnce sync.Once
	file_corepb_proto_rawDescData []byte
)

func file_corepb_proto_rawDescGZIP() []byte {
	file_corepb_proto_rawDescOnce.Do(func() {
		file_corepb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_corepb_proto_rawDesc), len(file_corepb_proto_rawDesc)))
	})
	return file_corepb_proto_rawDescData
}

var file_corepb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_corepb_proto_goTypes = []any{
	(*Item)(nil),    // 0: corepb.Item
	(*ItemChg)(nil), // 1: corepb.ItemChg
	(*ItemBag)(nil), // 2: corepb.ItemBag
}
var file_corepb_proto_depIdxs = []int32{
	0, // 0: corepb.ItemChg.item:type_name -> corepb.Item
	0, // 1: corepb.ItemBag.items:type_name -> corepb.Item
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_corepb_proto_init() }
func file_corepb_proto_init() {
	if File_corepb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_corepb_proto_rawDesc), len(file_corepb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_corepb_proto_goTypes,
		DependencyIndexes: file_corepb_proto_depIdxs,
		MessageInfos:      file_corepb_proto_msgTypes,
	}.Build()
	File_corepb_proto = out.File
	file_corepb_proto_goTypes = nil
	file_corepb_proto_depIdxs = nil
}
